### ISSUE TITLE
Block und Water Mlg bug

### ISSUE THREAD

**Issue by Stahli911** [HGLabor/training#12]
Wenn man den Block oder das Wasser am Boden setzt man aber nicht darauf landet bleibt der Block bzw. das Wasser dort.

**Comment by Krxwallo** [comment]
das ist client sided das ist wenn du wasser platzierst aber eig schon tot bist

**Comment by mooziii** [comment]
client sided and can be solved with a resend of the chunk (use a fabric mod to request this resend)
