### ISSUE TITLE
Fly Protection should be disabled

### ISSUE THREAD

**Issue by Stahli911** [HGLabor/training#13]
wenn du auf einem block der schon am boden stehst wie zum Beispiel eine Twisting Vine oder ein Scaffolding bist wirst du gekickt weil du angeblich herumgeflogen bist

**Comment by mooziii** [comment]
@Krxwallo yes but can be disabled in server-properties.

**Comment by Krxwallo** [comment]
hab disabled beim nächsten restart müsste es passen
