### ISSUE TITLE
Block Mlg Bug

### ISSUE THREAD

**Issue by Stahli911** [HGLabor/training#20]
du kannst mit dem Respawn anker auf dem Boden links klicken und so mit deinen Respawn point dort setzen wodurch du dauer haft auf dem Boden bleiben kannst

**Comment by polylymer** [comment]
Please do not report the same errors twice! Check before reporting if your issue already exists. 
 (https://github.com/HGLabor/training/issues/15)

**Comment by Stahli911** [comment]
der ist aber anderst weil beim anderen bist du unten nicht gestorben und konntest es dann machen aber da is es anderst

**Comment by ichmagmaenner4** [comment]
digga du reportest halt nur bugs die schon bekannt sind und das 456 455645665656575670650567067509670967906579056905649697ß05697u´ß04569ß50697´ß09354678ß0´9764523ß´09534670ß´945673ß90´3475690ß´7345690ß´537690ß´mal

**Comment by ichmagmaenner4** [comment]
kauft mir jemand evtl. eine neue tastatur?? B)

**Comment by Hotkeyyy** [comment]
ja B)

**Comment by Stahli911** [comment]
ichmagmaenner4 ich will bloß helfen es bug frei zu machen tut mir leid damit ich bugs reporte damit der server nicht mehr so viele bugs hat
