### ISSUE TITLE
durch nach dem tod gesetzte leiter auf dem Boden laufen ohne zu sterben (ladder mlg)

### ISSUE THREAD

**Issue by Stahli911** [HGLabor/training#21]
Wenn man eine Leiter/Vine nach dem tod setzt <-(ist client sided so weit ich weiß) und dann darauf springt kann man auf dem boden laufen ohne zurück teleportiert zu werden

**Comment by Krxwallo** [comment]
Yo kann man net viel machen ist ja client sided
