### ISSUE TITLE
Bug der Visible settings

### ISSUE THREAD

**Issue by Stahli911** [HGLabor/training#24]
Sorry aber weiß nicht wo ich es hin schreiben soll
Wenn man die Spieler Unsichtbar macht und ein neuer Spieler joint sieht man diesen 
Idee für diese Settings wie auf gomme ein item ins Inventar um die settings zu changen

**Comment by Indikativ** [comment]
iten ist meiner meinung nach nicht gut

**Comment by Krxwallo** [comment]
https://github.com/bluefireoly/HGLaborLobbyRemastered/issues
