### ISSUE TITLE
Mehr recraft für damager

### ISSUE THREAD

**Issue by realjarek** [HGLabor/training#26]
Ich fände es nice wenn man wie auf dojo mehrere stacks recraft mit in den damager nehmen könnte und auch andere recraft sorten(kakteen, kakaobohnen).
Vllt könnte man ein feature adden, dass man sein inventar ändern und abspeichern kann.
Man müsste natürlich auch ändern dass man nicht nach 96(glaube waren 96) suppen den damager geschafft hat.
Lg Jarek

**Comment by Indikativ** [comment]
nö
