### ISSUE TITLE
Gladiator macht faxxen

### ISSUE THREAD

**Issue by NooMacroo** [HGLabor/training#7]
Wenn man in HG im Gladiator Kampf ist kann man dort platzierte Blöcke nicht mehr abbauen

**Comment by r0yzer** [comment]
ja das nervt mich auch immer beim mlg üben

**Comment by r0yzer** [comment]
ich raff immer noch nicht wie du mod werden kannst auch als troll wie hat hotpvp das ausgehalten ich beh behindert hier noch
